sudo: false
language: android
jdk: oraclejdk8

before_install:
  - wget http://services.gradle.org/distributions/gradle-2.14.1-bin.zip
  - unzip gradle-2.14.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.14.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk -a --no-ui --filter tool,platform-tool,build-tools-25.0.0
  - git clone https://github.com/cbitstech/anthracite-clients-android.git
  - mv anthracite-clients-android ..

script:
  - gradle assembleDebug

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    # - build-tools-24

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-24
    # - sys-img-x86-android-24

